### ISSUE TITLE
Hacktoberfest challenge issues

### ISSUE THREAD

**Issue by rcvaram** [rcvaram/All_language_codes#1]
Here You can commit your hello world program to complex program for the first PR of the hacktoberfest challenge.
Don't forget to give a star and fork the repository

**Comment by cvaram96** [comment]
When you fork the repository, add the star to make visible this repository and share to your friends

**Comment by Aveesh52** [comment]
Can i contribute to this issue?

**Comment by cvaram96** [comment]
@Aveesh52 you can

**Comment by adarsh1mehra** [comment]
i have contributed named binary search python

**Comment by AlecsisDuarte** [comment]
I just **pull requested** a dart BST #71

**Comment by chakravarthi-v** [comment]
@rcvaram can I contribute for this repo now

**Comment by rcvaram** [comment]
Yes you can bro
